# Generated by Django 4.1.6 on 2023-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tipo', models.TextField(max_length=255, verbose_name='Tipo')),
                ('direccion', models.TextField(max_length=255, verbose_name='Direccion')),
                ('telefono', models.TextField(max_length=255, verbose_name='Telefono')),
                ('personaContacto', models.TextField(max_length=255, verbose_name='Persona de contacto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
        ),
    ]
