# Generated by Django 4.1.6 on 2023-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='personaContacto',
            field=models.CharField(max_length=255, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefono',
            field=models.CharField(max_length=255, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tipo',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
    ]
