# Generated by Django 4.1.6 on 2023-02-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_camion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='kilometros',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='precio',
            field=models.FloatField(),
        ),
    ]
