# Generated by Django 4.1.5 on 2023-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0002_alter_categorias_options_alter_receta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categorias',
            field=models.ManyToManyField(to='recetario.categorias', verbose_name='categorias'),
        ),
    ]
